on: release
name: Released
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Labeler
        uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
