on: push
name: Test
jobs:
  release:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Release GitHub Actions
        uses: technote-space/release-github-actions@test
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_COMMAND: 'yarn install && yarn build && yarn install --production'
